# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41d6eb8c7c8b17a6688fc2849d5ef5f190d58c4c42a3963bd275ea311d0a675e1fb40a8517b9216d37bfcbfed7fe97d2952bf63615cce53186a24aeb65998c4

test:
  secret_key_base: ef9eb6fb802c2ae59394029eccd2763380a7f5bcdf4ef4fd0912bd807a15fd3570ed60be137290787507315fc5c287bb0782c1aa4593d166986a22220f08ecd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
